import "../styles/globals.css";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import Navbar from "../common/navbar";

import type { AppProps } from "next/app";
import { Box } from "@mui/material";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <div className="container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
          <Navbar />
        </header>

        <main>
          <Box sx={{height: '100%', width: '100%'}}>
            <Component {...pageProps} />
          </Box>
        </main>

        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className="logo">
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
      <style jsx>{`
        header {
          flex: 0 0 auto;
          width: 100%;
        }
        .container {
          min-height: 100vh;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          height: 100vh;
        }

        main {
          flex: 1;
          min-height: 0;
          width: 100%;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }

        footer {
          flex: 0 0 auto;
          width: 100%;
          height: 100px;
          border-top: 1px solid #eaeaea;
          display: flex;
          justify-content: center;
          align-items: center;
        }

        footer a {
          display: flex;
          justify-content: center;
          align-items: center;
          flex-grow: 1;
        }

        .logo {
          height: 1em;
          margin-left: 0.5rem;
        }
      `}</style>
    </>
  );
}
export default MyApp;
